### ISSUE TITLE
Korektoj por Fundamento

### ISSUE THREAD

**Issue by RobinvanderVliet** [revuloj/voko-cikado#2]
En la dosiero `fundamento.xml` mi trovis 94 erarojn en la nacilingvaj tradukoj. Mi trovis ilin surbaze de [ĉi tiu skanaĵo](https://commons.wikimedia.org/wiki/File:Fundamento_de_Esperanto.djvu) de la Fundamento.

Ĉi tie mi listigas ilin:

| kapvorto | lingvo | eraro | korekto |
| --- | --- | --- | --- |
| aĵ' | fr | : | ; |
| altern' | pl | zmianiać | zmieniać |
| amik' | ru | друг | другъ |
| ark'aĵ' | pl | sklepiente | sklepienie |
| balustrad' | de | Geländar | Geländer |
| bapt'o'patr' | pl | chrestny | chrzestny |
| barakt' | fr | gigotler | gigotter |
| bazar' | fr | marché foire | marché, foire |
| bazar' | en | market fair | market, fair |
| blat' | fr | (ins) | (ins). |
| bram' | fr | brême | brème |
| ĉel' | fr | ceilule | cellule |
| ĉen' | fr | chaine | chaîne |
| ci | fr | tu, toi, | tu. toi, |
| ĉirkaŭ'skrib' | de | umschreibcn | umschreiben |
| datur' | pl | dziędzierzava | dziędzierzawa |
| de'log' | pl | zwodzić; uwieżć | zwodzić, uwieżć |
| de'pend' | pl | zaleźeć | zależeć |
| detru' | pl | burzyd | burzyć |
| efik' | pl | skutkonwać | skutkować |
| eg' | en | e. g, | e. g. |
| episkop' | de | Bishof | Bischof |
| esenc' | pl | islota | istota |
| fanfaron' | fr | glorieur | glorieux |
| fel' | pl | skora | skóra |
| flok' | en | fluck | flock |
| flok' | pl | kłaczet | kłaczek |
| ĝen' | de | genireu | geniren |
| ha! | ru | ахъ! | ахъ |
| hipokrit' | fr | l'hypoćrite | l'hypocrite |
| ho! | ru | охъ! | охъ |
| i | en | intinitive | infinitive |
| i | de | Intinitiv | Infinitiv |
| instig' | pl | odniecać | podniecać |
| kaleŝ' | fr | carosse calèche | carosse, calèche |
| kiu | fr | qui lequel | qui, lequel |
| komisi' | fr | de... | de.. |
| konscienc' | fr | consciénce | conscience |
| korb' | fr | panier corbeille | panier, corbeille |
| korp' | pl | cialo | ciało |
| kov' | en | broed | brood |
| krist'an | pl | chrześci janin | chrześcijanin |
| krud' | fr | rudé | rude |
| kubut' | de | Eltbogen | Ellbogen |
| kul' | fr | cousin moucheron | cousin, moucheron |
| kuraĝ' | pl | smialy | śmialy |
| l', la | fr | (le, la, les | (le, la, les) |
| l', la | de | Arttkel | Artikel |
| laf' | fr | lava | lave |
| laf' | pl | lawa | ława |
| libr' | pl | księga; książka | księga, książka |
| lojt' | pl | mięlus | miętus |
| maiz' | fr | mais | maïs |
| maleol' | fr | ceville | cheville |
| mantel' | pl | plaszcz | płaszcz |
| mard' | pl | wterek | wtorek |
| marŝ' | pl | marzerować | maszerować |
| memor' | de | Gedachtniss | Gedächtniss |
| migdal' | pl | migdal | miglał |
| murmur' | pl | mruczеć | mruczeć |
| mus' | pl | mysź | mysz |
| nobl' | en | (adj) | (adj.) |
| nu | pl | no!. | no! |
| ornam' | ru | наряждать | наряжать |
| per | pl | pwzez | przez |
| pik'il' | fr | aignillon | aiguillon |
| pland' | en | (of the foot) | (of the foot |
| plumb' | en | metall | metal |
| pren'o | de | kartensp. | Kartensp. |
| produkt' | fr | produite | produire |
| rembur' | fr | rembourer | rembourrer |
| rib' | fr | grosille | groseille |
| rifuz' | pl | odmanwiać | odmawiać |
| rikolt' | fr | moissoner | moissonner |
| safir' | pl | szalir | szafir |
| sal'amoniak' | fr | sal ammoniac | sel ammoniac |
| salon' | fr | salun | salon |
| skal' | pl | ). | ) |
| ŝtal' | en | steet | steel |
| ŝtof' | pl | sztof (miara) | materya |
| sub'aĉet' | pl | przekupyvać | przekupywać |
| sukcen' | fr | ambre joune | ambre jaune |
| supoz' | en | supose | suppose |
| tag'mez' | pl | poludnie | południe |
| ten'il' | de | Griftf | Griff |
| tiam | pl | wtedv | wtedy |
| ton' | pl | tom | ton |
| um' | pl | stlałego | stałego |
| ve! | pl | och!. | och! |
| vert' | en | ot the head | of the head |
| vesper'manĝ' | pl | wieczerrzać | wieczerzać |
| vikari' | pl | zastępcar | zastępca |

**Comment by wdiestel** [comment]
Dankon, mi korektis la plej multajn. Kelkajn mi ne korektis, eble ili estas eraroj en la referenca skanaĵo aŭ estas pro al alia eldono. Punkto fine de ĉiu vortarero aldoniĝas aŭtomate per XSL, do mi ne povas ĝustigi tion en la fonto, eble oni povus adapti la transformregulon, ke ĝi ne metos punkton post ")" aŭ "!"
